### ISSUE TITLE
Insights for asynchronous operations

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#160]
1. Discover asynchronous operations by finding spans that end after their parent
2. If the request had asynchronous operations show a different request breakdown insight
3. In the duration breakdown, add the tag ' async' in the duration breakdown insight for spans with greater end time 

See the request breakdown version for async:
https://www.figma.com/file/9WRmS8uKjUIv45ldWun2pt/UI---Shared?type=design&node-id=1075%3A241920&mode=design&t=VTioZBRq6unlwWsZ-1

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/a04dda83-bffd-49f8-8886-7bb0ab623bf3)

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/d0ce471a-30e4-499e-aa35-a1d8ebbf63bf)

**Comment by arik-dig** [comment]
@doppleware few questions mainly related to the backend:

1) If I understand correctly this issue relates to Endpoint, right? and not any arbitrary span, right?

assuming answer is yes

1A) so we're going to check for ANY span within a trace which has endtime greater than endtime of the endpoint.

1B) I guess this 'async' indication is stored per endpoint.
 but what happens if an endpoint was 'sync' and after code change now its 'async'. those transitions should be tracked as well, isn't it? I guess we should apply so statistics algo to determine such isn't it?
or maybe you think that any given time we should maintain possibly 2 type of unsights one for 'sync' and one for 'async'
lets discuss

2) about the duration insight itself.

2A) is it related to the 'async' state as mentioned in bullet 1B?

2B) if its not related to endpoint, so does it relate to child spans that have async nature, or maybe parent spans, which affect me as a child? its not clear

**Comment by doppleware** [comment]
1. There are two different insight changes here. The breakdown insight is relevant to endpoints only (because we only show it for endpoints). The duration insight async mark is relevant for any span whose duration exceeds its parent.
1A. For the endpoint yes. Consider that we are showing the duration of the TRACE not the endpoint in the breakdown insight.
1B. No statistics, its enough to have one such instance in the measured period (where the descendant exceeded the endpoint).

2A. Duration is the other way around, we show it on the span that exceeded its parent, so not on the endpoint.
2B. Its the async span itself - the one that has a duration later than its parent.

**Comment by arik-dig** [comment]
@doppleware reg SpanDuration insight itself.
I remind that we decided to identify `isAsync` in the span_flows with this naive formula:
`IsAsync = span.endTime > span.parent.endTime` 

3. I think its too naive approach and I think that we need to look and compare
for` this.serviceName and parent.serviceName` - because even locally I encountered "clock skew adjustment" which I saw in jaeger and it cause SYNC span to to appear as ASYNC...

4. For same process, i guess that we could try to search for different threadName (it supposed to work for java)

**Comment by kshmidt-digma** [comment]
@doppleware 

Could you please explain the meaning of the progress bar values in the screenshot example above and how percentages should be calculated?

Do we treat the longest span (`Rendering`) like 100% and calculate all other span fractions relying on their durations in comparison with the longest one?
