### ISSUE TITLE
Add carousel to Recent activity environment panel

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#50]
Mockups: https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?node-id=1129-170553&t=uT9PTv2cF01dO9Jm-0

**Comment by doppleware** [comment]
We shouldn't show the carousel arrows when there is no real navigation between multiple pages. Also, now whenever you click an environment the view scrolls up a bit so that it becomes unaligned with the top:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/93863/231541966-ab6e92be-2a47-4eb2-858b-b1dd82134efc.png">
