### ISSUE TITLE
Collect user email in wizard

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-ui#67]
Add an optional 'Email' field to the last step of the wizard.

**Comment by asafchen-dig** [comment]
In order to send the **email** to the java-side, when he user clicks on the **Finish** button, I'm suggesting to add to `INSTALLATION_WIZARD/FINISH` message a payload that looks like this:
``` json
{
   "email": "..."
}
```

There is a branch ready to test (and merge) that goes by this logic: 
https://github.com/digma-ai/digma-intellij-plugin/pull/580
