### ISSUE TITLE
Error Details tab doesn't fit to the box

### ISSUE THREAD

**Issue by ohrebeniuk** [digma-ai/digma-ui#788]
<img width="619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEp4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33f1627b84ac57008286bd03e769ee3b28ddc752/image.png" alt="image.png" />

**Comment by kshmidt-digma** [comment]
This happens because there is not enough space to display the "Error Details" string in a single line.

There are several solutions to consider:
1) Rename the tab from "Error Details" to "Errors"
2) Truncate the name of the tab with ellipsis
3) Show the title in 2 lines (as it will require the tab height to change, we would need to merge Navigation and Main app first to avoid the vertical scrollbar)

FYI @shaykeren
